justauth:
  enabled: true
  extend:
    enum-class: com.xkcoding.justauthspringbootstarterdemo.extend.ExtendSource
    config:
      TEST:
        request-class: com.xkcoding.justauthspringbootstarterdemo.extend.ExtendTestRequest
        client-id: xxxxxx
        client-secret: xxxxxxxx
        redirect-uri: http://oauth.xkcoding.com/demo/oauth/test/callback
      WEB_ENTERPRISE_WE_CHAT:
        request-class: com.xkcoding.justauthspringbootstarterdemo.extend.WebEnterpriseWeChatRequest
        client-id: ww58**********6fbc
        client-secret: 8G6PCr0****************************yzaPc78
        redirect-uri: http://oauth.xkcoding.com/demo/oauth/web_enterprise_we_chat/callback
        agent-id: 1000002
  type:
    QQ:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/qq/callback
    WECHAT_ENTERPRISE:
      client-id: ww58**********6fbc
      client-secret: 8G6PCr0****************************yzaPc78
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat_enterprise/callback
      agent-id: 1000002
    DINGTALK:
      client-id: ding*************cl3
      client-secret: fz_NeJh9S***************************************XduEx4nyG8ZFiMD
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/dingtalk/callback
  cache:
    type: default
    prefix: 'demo::'
    timeout: 1h
server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  redis:
    host: localhost
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
logging:
  level:
    com.xkcoding: debug